{{ docker.from("php-apache", "8.3") }}

{{ docker.platformArgs() }}

{{ environment.web() }}
{{ environment.webPhp() }}
{{ environment.webDevelopment() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php.officialDevelopment(version="8.3") }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
