{{ docker.from("bootstrap", "ubuntu-15.04", user) }}

{{ docker.platformArgs() }}

{{ environment.base() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ base.ubuntu() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}

{{ docker.entrypoint("/entrypoint") }}
{{ docker.cmd("supervisord") }}
