name: 'Docker Composite Build'
description: 'qemu + buildx + ghcr.io login + docker-build-push'
inputs:
  registry-user:
    description: ghcr.io user
    required: true

  registry-secret:
    description: ghcr.io token
    required: true

  image-name:
    description: 'docker image name'
    required: true
  
  image-context:
    description: 'docker image context path'
    required: true

  image-platforms:
    description: 'docker image platforms'
    required: false
    default: 'linux/amd64,linux/arm64'

  image-tags:
    description: 'docker image tags'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Set up QEMU"
      uses: docker/setup-qemu-action@v2

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v2

    - name: "Login to ghcr.io"
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ inputs.registry-user }}
        password: ${{ inputs.registry-secret }}

    - name: Build ${{ inputs.image-name }}
      uses: docker/build-push-action@v3
      with:
        context: ${{ inputs.image-context }}
        platforms: ${{ inputs.image-platforms }}
        push: true
        tags: ${{ inputs.image-tags }}
