{{ docker.from("base", "debian-9", user) }}

{{ docker.platformArgs() }}

{{ environment.baseApp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ baseapp.debian9() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
