{{ docker.fromOfficial("alpine") }}

{{ docker.platformArgs() }}

{{ docker.copy("/baselayout", "/baselayout", docker.image("base-layout", user=user)) }}

RUN set -eux; \
    apk add --no-cache \
        ca-certificates \
        dpkg \
        openssl \
        curl \
        bash \
        sed \
        wget \
        zip \
        unzip \
        bzip2 \
        p7zip \
        drill \
        ldns \
        openssh-client \
        rsync \
        git \
        gnupg \
    ; \
