{{ docker.from("base", "alpine", user) }}

{{ docker.platformArgs() }}

{{ varnish.env() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ varnish.alpine() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}

{{ docker.cmd("varnishd") }}

{{ docker.expose('80') }}
