{{ docker.from("base", "debian-10", user) }}

{{ environment.baseApp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ baseapp.debian10() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
