{{ docker.from("base", "ubuntu-16.10", user) }}

{{ environment.baseApp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ baseapp.ubuntu() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
