{{ docker.from("base", "alpine", user) }}

{{ environment.baseApp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ baseapp.alpine() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
