{{ docker.from("php", "7.3-alpine", user) }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php.officialDevelopmentAlpine(version="7.3") }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
