{{ docker.fromOfficial("debian", "buster-slim") }}

{{ docker.platformArgs() }}

RUN mkdir -p \
    /baselayout/bin \
    /baselayout/usr/local/bin

{{ docker.copy("/baselayout", "/baselayout", docker.image("base-layout", user=user)) }}

RUN set -eux; \
        apt-get update; \
        apt-get install -y --no-install-recommends \
        ca-certificates \
        dpkg \
        openssl \
        curl \
        sed \
        wget \
        zip \
        unzip \
        bzip2 \
        p7zip \
        ldnsutils \
        libldns2 \
        openssh-client \
        rsync \
        git \
        gnupg \
    ; \
    rm -rf /var/lib/apt/lists/* ; \
    mkdir -p \
        /baselayout/sbin \
        /baselayout/usr/local/bin \
        {{ tools.goreplace(path="/baselayout/usr/local/bin") }} \
        {{ tools.gosu(path="/baselayout/sbin") }}
