{{ docker.from("php", "8.2-alpine", user) }}

{{ docker.platformArgs() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php.officialDevelopmentAlpine(version="8.2") }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
