{{ docker.from("php", "5.6", user) }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php.officialDevelopment(version="5.6") }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
