{{ docker.from("bootstrap", "alpine", user) }}

{{ docker.platformArgs() }}

{{ docker.volume('/etc/letsencrypt') }}
{{ docker.volume('/var/www') }}

RUN set -x \
    {{ certbot.alpine() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
