{{ docker.from("php", "8.2", user) }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php.officialDevelopment(version="8.2") }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
