{{ docker.fromOfficial("ubuntu", "15.04") }}

{{ docker.platformArgs() }}

{{ docker.version() }}

{{ environment.general() }}

{{ baselayout.copy() }}

RUN set -x \
    {{ bootstrap.ubuntuOld() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
