{{ docker.from("php", "ubuntu-18.04", user) }}

{{ docker.platformArgs() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ php7dev.ubuntu() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}
