{{ docker.from("php", "centos-7", user) }}

{{ environment.web() }}
{{ environment.webPhp() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ apache.centos() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}

{{ docker.expose('80 443') }}
