{{ docker.from("bootstrap", "alpine", user) }}

{{ docker.platformArgs() }}

{{ environment.base() }}

{{ docker.copy('conf/', '/opt/docker/') }}

RUN set -x \
    {{ base.alpine() }} \
    {{ provision.runBootstrap() }} \
    {{ docker.cleanup() }}

{{ docker.entrypoint("/entrypoint") }}
{{ docker.cmd("supervisord") }}
