name: docker images

on:
  push:
    branches:
      - 'main'
      - 'experimental/gh-actions'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: build and push "php-apache:8.0-alpine"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-apache/8.0-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-apache:8.0-alpine"
      
      - name: build and push "php-apache:8.0"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-apache/8.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-apache:8.0"
      
      - name: build and push "php-apache-dev:8.0-alpine"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-apache-dev/8.0-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-apache-dev:8.0-alpine"
      
      - name: build and push "php-apache-dev:8.0"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-apache-dev/8.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-apache-dev:8.0"
      
      - name: build and push "php-official:8.0-alpine"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-official/8.0-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-official:8.0-alpine"
      
      - name: build and push "php-official:8.0"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-official/8.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-official:8.0"
      
      - name: build and push "php-nginx-dev:8.0-alpine"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-nginx-dev/8.0-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-nginx-dev:8.0-alpine"
      
      - name: build and push "php-nginx-dev:8.0"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-nginx-dev/8.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-nginx-dev:8.0"
      
      - name: build and push "php-nginx:8.0-alpine"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-nginx/8.0-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-nginx:8.0-alpine"
      
      - name: build and push "php-nginx:8.0"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-nginx/8.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-nginx:8.0"
      
      - name: build and push "php-dev:8.0-alpine"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-dev/8.0-alpine
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-dev:8.0-alpine"
      
      - name: build and push "php-dev:8.0"
        uses: docker/build-push-action@v3
        with:
          context: docker/php-dev/8.0
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "ghcr.io/cocoastorm/webdevops/php-dev:8.0"
      
