name: docker images

on:
  push:
    branches:
      - 'main'
      - 'experimental/gh-actions'

concurrency:
  group: "${{ github.ref }}"

permissions:
  contents: read

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.generate-matrix.outputs.matrix-base }}
      multi: ${{ steps.generate-matrix.outputs.matrix-multi }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r bin/requirements.txt

      - name: Generate Matrix
        id: generate-matrix
        run: python bin/console generate:gh-action-matrix --whitelist='toolbox' --whitelist='php-*/8.*/*'
  
  build-base-images:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.base) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Docker Build Composite
        uses: ./.github/actions/composite-docker
        with:
          registry-user: ${{ github.repository_owner }}
          registry-secret: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ matrix.name }}
          image-context: ${{ matrix.context }}
          image-tags: ${{ matrix.tags }}

  build-multi-images:
    needs:
      - generate-matrix
      - build-base-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.multi) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build Composite
        uses: ./.github/actions/composite-docker
        with:
          registry-user: ${{ github.repository_owner }}
          registry-secret: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ matrix.name }}
          image-context: ${{ matrix.content }}
          image-tags: ${{ matrix.tags }}

