name: docker images

on:
  push:
    branches:
      - 'main'
      - 'experimental/gh-actions'

concurrency:
  group: "${{ github.ref }}"

permissions:
  contents: read

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.output-base-matrix.outputs.base }}
      multi: ${{ steps.output-multi-matrix.outputs.multi }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - run: pip install -r bin/requirements.txt

      - name: Generate Matrix
        run: python bin/console generate:gh-action-matrix --whitelist='toolbox' --whitelist='php-*/8.*/*'

      - name: Output Base Matrix
        id: output-base-matrix
        run: |
          JSON=$(cat ./gh_matrix-base-images.json)
          echo "::set-output name=base::$JSON"
      
      - name: Output Multi Matrix
        id: output-multi-matrix
        run: |
          JSON=$(cat ./gh_matrix-multi-images.json)
          echo "::set-output name=multi::$JSON"
  
  build-base-images:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.base) }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Docker Build Composite
        uses: ./.github/actions/composite-docker
        with:
          image-name: ${{ matrix.name }}
          image-context: ${{ matrix.context }}
          image-tags: ${{ matrix.tags }}

  build-multi-images:
    needs:
      - generate-matrix
      - build-base-images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.multi) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Build Composite
        uses: ./.github/actions/composite-docker
        with:
          image-name: ${{ matrix.name }}
          image-context: ${{ matrix.content }}
          image-tags: ${{ matrix.tags }}

